package com.sps.entity.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.o_id
	 *
	 * @mbggenerated
	 */
	private Integer oId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.orderid
	 *
	 * @mbggenerated
	 */
	private String orderid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.shopkeeper
	 *
	 * @mbggenerated
	 */
	private String shopkeeper;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.shopkeepername
	 *
	 * @mbggenerated
	 */
	private String shopkeepername;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.selfemployed
	 *
	 * @mbggenerated
	 */
	private String selfemployed;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.selfname
	 *
	 * @mbggenerated
	 */
	private String selfname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.scale
	 *
	 * @mbggenerated
	 */
	private Integer scale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.createtime
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.flag
	 *
	 * @mbggenerated
	 */
	private Integer flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.payment
	 *
	 * @mbggenerated
	 */
	private BigDecimal payment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.isdelete
	 *
	 * @mbggenerated
	 */
	private Integer isdelete;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.remark
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.money
	 *
	 * @mbggenerated
	 */
	private Long money;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.servicescale
	 *
	 * @mbggenerated
	 */
	private Double servicescale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.servicemoney
	 *
	 * @mbggenerated
	 */
	private Long servicemoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.phone
	 *
	 * @mbggenerated
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.address
	 *
	 * @mbggenerated
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.modifytime
	 *
	 * @mbggenerated
	 */
	private Date modifytime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.sum_money
	 *
	 * @mbggenerated
	 */
	private Long sumMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sps_order.unit
	 *
	 * @mbggenerated
	 */
	private String unit;

	private List<OrderGoods> orderGoods;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table sps_order
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.o_id
	 *
	 * @return the value of sps_order.o_id
	 *
	 * @mbggenerated
	 */
	public Integer getoId() {
		return oId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.o_id
	 *
	 * @param oId
	 *            the value for sps_order.o_id
	 *
	 * @mbggenerated
	 */
	public void setoId(Integer oId) {
		this.oId = oId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.orderid
	 *
	 * @return the value of sps_order.orderid
	 *
	 * @mbggenerated
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.orderid
	 *
	 * @param orderid
	 *            the value for sps_order.orderid
	 *
	 * @mbggenerated
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.shopkeeper
	 *
	 * @return the value of sps_order.shopkeeper
	 *
	 * @mbggenerated
	 */
	public String getShopkeeper() {
		return shopkeeper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.shopkeeper
	 *
	 * @param shopkeeper
	 *            the value for sps_order.shopkeeper
	 *
	 * @mbggenerated
	 */
	public void setShopkeeper(String shopkeeper) {
		this.shopkeeper = shopkeeper == null ? null : shopkeeper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.shopkeepername
	 *
	 * @return the value of sps_order.shopkeepername
	 *
	 * @mbggenerated
	 */
	public String getShopkeepername() {
		return shopkeepername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.shopkeepername
	 *
	 * @param shopkeepername
	 *            the value for sps_order.shopkeepername
	 *
	 * @mbggenerated
	 */
	public void setShopkeepername(String shopkeepername) {
		this.shopkeepername = shopkeepername == null ? null : shopkeepername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.selfemployed
	 *
	 * @return the value of sps_order.selfemployed
	 *
	 * @mbggenerated
	 */
	public String getSelfemployed() {
		return selfemployed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.selfemployed
	 *
	 * @param selfemployed
	 *            the value for sps_order.selfemployed
	 *
	 * @mbggenerated
	 */
	public void setSelfemployed(String selfemployed) {
		this.selfemployed = selfemployed == null ? null : selfemployed.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.selfname
	 *
	 * @return the value of sps_order.selfname
	 *
	 * @mbggenerated
	 */
	public String getSelfname() {
		return selfname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.selfname
	 *
	 * @param selfname
	 *            the value for sps_order.selfname
	 *
	 * @mbggenerated
	 */
	public void setSelfname(String selfname) {
		this.selfname = selfname == null ? null : selfname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.scale
	 *
	 * @return the value of sps_order.scale
	 *
	 * @mbggenerated
	 */
	public Integer getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.scale
	 *
	 * @param scale
	 *            the value for sps_order.scale
	 *
	 * @mbggenerated
	 */
	public void setScale(Integer scale) {
		this.scale = scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.createtime
	 *
	 * @return the value of sps_order.createtime
	 *
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.createtime
	 *
	 * @param createtime
	 *            the value for sps_order.createtime
	 *
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.flag
	 *
	 * @return the value of sps_order.flag
	 *
	 * @mbggenerated
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.flag
	 *
	 * @param flag
	 *            the value for sps_order.flag
	 *
	 * @mbggenerated
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.payment
	 *
	 * @return the value of sps_order.payment
	 *
	 * @mbggenerated
	 */
	public BigDecimal getPayment() {
		return payment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.payment
	 *
	 * @param payment
	 *            the value for sps_order.payment
	 *
	 * @mbggenerated
	 */
	public void setPayment(BigDecimal payment) {
		this.payment = payment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.isdelete
	 *
	 * @return the value of sps_order.isdelete
	 *
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.isdelete
	 *
	 * @param isdelete
	 *            the value for sps_order.isdelete
	 *
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.remark
	 *
	 * @return the value of sps_order.remark
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.remark
	 *
	 * @param remark
	 *            the value for sps_order.remark
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.money
	 *
	 * @return the value of sps_order.money
	 *
	 * @mbggenerated
	 */
	public Long getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.money
	 *
	 * @param money
	 *            the value for sps_order.money
	 *
	 * @mbggenerated
	 */
	public void setMoney(Long money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.servicescale
	 *
	 * @return the value of sps_order.servicescale
	 *
	 * @mbggenerated
	 */
	public Double getServicescale() {
		return servicescale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.servicescale
	 *
	 * @param servicescale
	 *            the value for sps_order.servicescale
	 *
	 * @mbggenerated
	 */
	public void setServicescale(Double servicescale) {
		this.servicescale = servicescale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.servicemoney
	 *
	 * @return the value of sps_order.servicemoney
	 *
	 * @mbggenerated
	 */
	public Long getServicemoney() {
		return servicemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.servicemoney
	 *
	 * @param servicemoney
	 *            the value for sps_order.servicemoney
	 *
	 * @mbggenerated
	 */
	public void setServicemoney(Long servicemoney) {
		this.servicemoney = servicemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.phone
	 *
	 * @return the value of sps_order.phone
	 *
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.phone
	 *
	 * @param phone
	 *            the value for sps_order.phone
	 *
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.address
	 *
	 * @return the value of sps_order.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.address
	 *
	 * @param address
	 *            the value for sps_order.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.modifytime
	 *
	 * @return the value of sps_order.modifytime
	 *
	 * @mbggenerated
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.modifytime
	 *
	 * @param modifytime
	 *            the value for sps_order.modifytime
	 *
	 * @mbggenerated
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.sum_money
	 *
	 * @return the value of sps_order.sum_money
	 *
	 * @mbggenerated
	 */
	public Long getSumMoney() {
		return sumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.sum_money
	 *
	 * @param sumMoney
	 *            the value for sps_order.sum_money
	 *
	 * @mbggenerated
	 */
	public void setSumMoney(Long sumMoney) {
		this.sumMoney = sumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.name
	 *
	 * @return the value of sps_order.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.name
	 *
	 * @param name
	 *            the value for sps_order.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sps_order.unit
	 *
	 * @return the value of sps_order.unit
	 *
	 * @mbggenerated
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sps_order.unit
	 *
	 * @param unit
	 *            the value for sps_order.unit
	 *
	 * @mbggenerated
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	public List<OrderGoods> getOrderGoods() {
		return orderGoods;
	}

	public void setOrderGoods(List<OrderGoods> orderGoods) {
		this.orderGoods = orderGoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sps_order
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Order other = (Order) that;
		return (this.getoId() == null ? other.getoId() == null : this.getoId().equals(other.getoId()))
				&& (this.getOrderid() == null ? other.getOrderid() == null
						: this.getOrderid().equals(other.getOrderid()))
				&& (this.getShopkeeper() == null ? other.getShopkeeper() == null
						: this.getShopkeeper().equals(other.getShopkeeper()))
				&& (this.getShopkeepername() == null ? other.getShopkeepername() == null
						: this.getShopkeepername().equals(other.getShopkeepername()))
				&& (this.getSelfemployed() == null ? other.getSelfemployed() == null
						: this.getSelfemployed().equals(other.getSelfemployed()))
				&& (this.getSelfname() == null ? other.getSelfname() == null
						: this.getSelfname().equals(other.getSelfname()))
				&& (this.getScale() == null ? other.getScale() == null : this.getScale().equals(other.getScale()))
				&& (this.getCreatetime() == null ? other.getCreatetime() == null
						: this.getCreatetime().equals(other.getCreatetime()))
				&& (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
				&& (this.getPayment() == null ? other.getPayment() == null
						: this.getPayment().equals(other.getPayment()))
				&& (this.getIsdelete() == null ? other.getIsdelete() == null
						: this.getIsdelete().equals(other.getIsdelete()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
				&& (this.getServicescale() == null ? other.getServicescale() == null
						: this.getServicescale().equals(other.getServicescale()))
				&& (this.getServicemoney() == null ? other.getServicemoney() == null
						: this.getServicemoney().equals(other.getServicemoney()))
				&& (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getModifytime() == null ? other.getModifytime() == null
						: this.getModifytime().equals(other.getModifytime()))
				&& (this.getSumMoney() == null ? other.getSumMoney() == null
						: this.getSumMoney().equals(other.getSumMoney()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sps_order
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getoId() == null) ? 0 : getoId().hashCode());
		result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
		result = prime * result + ((getShopkeeper() == null) ? 0 : getShopkeeper().hashCode());
		result = prime * result + ((getShopkeepername() == null) ? 0 : getShopkeepername().hashCode());
		result = prime * result + ((getSelfemployed() == null) ? 0 : getSelfemployed().hashCode());
		result = prime * result + ((getSelfname() == null) ? 0 : getSelfname().hashCode());
		result = prime * result + ((getScale() == null) ? 0 : getScale().hashCode());
		result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
		result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
		result = prime * result + ((getPayment() == null) ? 0 : getPayment().hashCode());
		result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
		result = prime * result + ((getServicescale() == null) ? 0 : getServicescale().hashCode());
		result = prime * result + ((getServicemoney() == null) ? 0 : getServicemoney().hashCode());
		result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getModifytime() == null) ? 0 : getModifytime().hashCode());
		result = prime * result + ((getSumMoney() == null) ? 0 : getSumMoney().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sps_order
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", oId=").append(oId);
		sb.append(", orderid=").append(orderid);
		sb.append(", shopkeeper=").append(shopkeeper);
		sb.append(", shopkeepername=").append(shopkeepername);
		sb.append(", selfemployed=").append(selfemployed);
		sb.append(", selfname=").append(selfname);
		sb.append(", scale=").append(scale);
		sb.append(", createtime=").append(createtime);
		sb.append(", flag=").append(flag);
		sb.append(", payment=").append(payment);
		sb.append(", isdelete=").append(isdelete);
		sb.append(", remark=").append(remark);
		sb.append(", money=").append(money);
		sb.append(", servicescale=").append(servicescale);
		sb.append(", servicemoney=").append(servicemoney);
		sb.append(", phone=").append(phone);
		sb.append(", address=").append(address);
		sb.append(", modifytime=").append(modifytime);
		sb.append(", sumMoney=").append(sumMoney);
		sb.append(", name=").append(name);
		sb.append(", unit=").append(unit);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}